variables:
  agent-pool: 'Docker-pool'
  isPrimary: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  srcDir: '$(System.DefaultWorkingDirectory)/src'
  GO111MODULE: 'auto'

stages:
  - stage: Tests
    displayName: 'Tests'
    jobs:
      - job: Unit Tests
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: GoTool@0
            displayName: 'Set unit test packages'
            inputs:
              version: '1.19.2'
          - bash: |
              cd src/
              echo "##vso[task.setvariable variable=test_packages;]$(go list ./... | grep -v '/functional_tests/')"
          - task: Go@0
            displayName: 'Run tests'
            inputs:
              command: 'test'
              arguments: '$(test_packages)'
              workingDirectory: '$(srcDir)'
      - job: Unit Tests
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - bash: |
            docker-compose -f azure_pipelines/docker-compose.functional_tests.yml up -d
        - task: Go@0
          displayName: 'Functional tests'
          inputs:
            command: 'test'
            arguments: 'github.com/dfds/confluent-gateway/functional_tests'
            workingDirectory: '$(srcDir)'

  - stage: CD
    displayName: 'Build, test, deliver deployment artifacts'
    jobs:
      - job: CD
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: GoTool@0
            inputs:
              version: '1.19.2'
          - bash: |
              chmod +x ./tools/push-container.sh
              make cd BUILD_NUMBER="$(Build.BuildNumber)"              
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              ALLOW_PUSH_CONTAINER: $(ALLOW_PUSH_CONTAINER)
            displayName: 'make cd'
            condition: succeeded()
          - task: PublishBuildArtifacts@1
            displayName: "Publish Artifact: manifests"
            inputs:
              PathtoPublish: '$(System.DefaultWorkingDirectory)/.output/manifests'
              ArtifactName: manifests

  - stage: Deploy
    condition: and(succeeded(), eq(variables.isPrimary, true))
    dependsOn: CD
    displayName: 'Deployments'
    jobs:
      - job: Production
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: none
          - download: current
            artifact: manifests
            displayName: 'Download build artifacts'
          - publish: '$(Pipeline.Workspace)/manifests/'
            artifact: deployed-manifests
            displayName: 'Publish manifests'
          - task: Kubernetes@1
            displayName: kubectl apply
            inputs:
              connectionType: Kubernetes Service Connection
              kubernetesServiceEndpoint: Kubernetes-Hellman-selfservice-deploy
              cwd: '$(Pipeline.Workspace)/manifests/'
              command: apply
              arguments: -f .
