apiVersion: v1
kind: Service
metadata:
  name: {{ include "confluent-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.service.scrapeMetrics }}
    scrape-service-metrics: "true"
    {{- end }}
    {{- include "confluent-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "confluent-gateway.selectorLabels" . | nindent 4 }}
