apiVersion: v1
kind: Service
metadata:
  name: confluent-gateway
  namespace: selfservice
  # labels:
  #   scrape-service-metrics: "true"
spec:
  ports:
  - name: external
    port: 80
    targetPort: web
  selector:
    app: confluent-gateway