apiVersion: v1
kind: Service
metadata:
  name: confluent-gateway
  namespace: selfservice
  labels:
    scrape-service-metrics: "true"
spec:
  ports:
    - name: api
      port: 8080
      targetPort: api
    - name: metrics
      port: 8888
      targetPort: metrics

  selector:
    app: confluent-gateway
