version: "3.8"

services:

  database:
    image: postgres:latest
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=p

  pgup:
    build: ./../db
    depends_on:
    - database
    environment:
    - LOCAL_DEVELOPMENT=1           # will CREATE DATABASE ${PGDATABASE} every time
    - PGDATABASE=db                 # database name
    - PGHOST=database               # docker compose service name
    - PGUSER=postgres               # same as above
    - PGPASSWORD=p                  # same as above
    - PGSSLMODE=disable             # ignore SSLMODE for local development