name: Make auto PR

on:
  repository_dispatch:
    types: run-shared-workflow

jobs:
  run-shared-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Auto PR
        uses: dfds/shared-workflows/.github/workflows/automation-create-pull-request.yaml
        with:
          repository-owner: ${{ github.repository_owner }}
          repository-name: ${{ github.repository }}
          main-branch: main
          develop-branch: develop
